### PR TITLE
[RD-85] User may upload a pdf associated with a copyright application

### PR DESCRIPTION
**Pull request by lipsotiko**

### CODE REVIEW

**Comment by lipsotiko** [comment]
@jamesisaacs old habits are hard to break. I updated the api.py class and application review vue; also appended the "secure" filename to the GUID so files have this naming convention: eee0620e-49ee-11ea-b353-38baf84b98b2_A17_FlightPlan.pdf.

**Comment by jamesisaacs** [comment]
@lipsotiko LGTM. Just one thing, the entry for Flask-Babel in requirements.txt inadvertently (?) reverts PR #106

**Comment by lipsotiko** [comment]
@james I reverted Flask Babel because App Builder needed the previous version. The server wouldn’t run; I think we need to update both at the same time.

**Comment by jamesisaacs** [comment]
@lipsotiko Thanks. I see it now - 

ERROR: flask-appbuilder 2.2.2 has requirement Flask-Babel<1,>=0.11.1, but you'll have flask-babel 1.0.0 which is incompatible.

**Pull request merged**
