### PR TITLE
[RE-133] Formatting and refactoring of Application Review

### PR DESCRIPTION
**Pull request by lipsotiko**

### CODE REVIEW

**Comment by jamesisaacs** [comment]
@vango Looks good. Just a couple of small things, "Year of Birth" is present on the application review even when it's lacking a value, and the name should be [RD-131] ...

**Comment by lipsotiko** [comment]
@jamesisaacs I updated the component to conditionally render the year of birth. I also noticed the certificate address was listed twice. I added RD-131 to the commit message (I didn't realize there was a story for that)

**Comment by Vango** [comment]
Just wondering why my login name was used in the code.

**Comment by jamesisaacs** [comment]
@Vango I typed @ + Vango by accident. The other developer's name is Vango.

**Pull request merged**
